apiVersion: apps/v1
kind: Deployment
metadata:
  name:  blogs
  namespace: default
  labels:
    app:  blogs
spec:
  selector:
    matchLabels:
      app: blogs
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  blogs
  spec:
    containers:
    - name:  blogs
      image:  emn503/web-app-blogs:latest
      ports:
      - containerPort: 3000
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: blogs-service
  namespace: default
spec:
  selector:
    app: blogs
  type: NodePort
  ports:
  - name: blogs
    protocol: TCP
    port: 3052
    targetPort: 3002
    nodePort: 31002