kind: Deployment
apiVersion: apps/v1
metadata:
  name: blogs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogs
  template:
    metadata:
      labels:
        app: blogs
    spec:
      containers:
        - name: blogs
          image: emn503/web-app-blogs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: blogs-service
  namespace: default
spec:
  selector:
    app: blogs
  type: NodePort
  ports:
  - name: blogs
    protocol: TCP
    port: 3052
    targetPort: 3002
    nodePort: 31002