kind: Deployment
apiVersion: apps/v1
metadata:
  name: header
spec:
  replicas: 2
  selector:
    matchLabels:
      app: header
  template:
    metadata:
      labels:
        app: header
    spec:
      containers:
        - name: header
          image: emn503/web-header:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: header-service
  namespace: default
spec:
  selector:
    app: header
  type: NodePort
  ports:
  - name: header
    protocol: TCP
    port: 3051
    targetPort: 3001
    nodePort: 31001