apiVersion: apps/v1
kind: Deployment
metadata:
  name: container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: container
    strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: container
    spec:
      containers:
      - name: container
        image: emn503/web-container:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: container-service
  namespace: default
spec:
  selector:
    app: container
  type: NodePort
  ports:
  - name: container
    protocol: TCP
    port: 3050
    targetPort: 3000
    nodePort: 31000